#!/usr/bin/env python
import sys
import json
import argparse

from c4.board import Board, DRAW
from c4.engine import GreedyEngine, NegamaxEngine, \
    AlphaBetaEngine, ABCachedEngine, ABDeepEngine, \
    PVSEngine, PVSCachedEngine, PVSDeepEngine
from c4.game import GameHandler
from c4.arena import arena


engine_map = {
    'greedy': GreedyEngine,
    'negamax': NegamaxEngine,
    'alphabeta': AlphaBetaEngine,
    'abcached': ABCachedEngine,
    'abdeep': ABDeepEngine,
    'pvs': PVSEngine,
    'pvscached': PVSCachedEngine,
    'pvsdeep': PVSDeepEngine,
    }


def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(title='Commands', description='c4 builin commands')

    arena_parser = subparsers.add_parser('arena', help='Run arena')
    arena_parser.add_argument('config', metavar='CONFIGFILE',
                              type=argparse.FileType('r'))
    arena_parser.set_defaults(cmd=run_arena)

    bm_parser = subparsers.add_parser('bm', help='Select the bestmove')
    bm_parser.set_defaults(cmd=run_bm)
    bm_parser.add_argument('engine', metavar='ENGINE',
                           help='Engine to use. Format: engine_name:par1:par2:...')

    args = parser.parse_args()
    args.cmd(args)


def run_shell(args):
    pass


def run_arena(args):
    config = json.load(args.config)
    engines = []
    for engine_cfg in config:
        engine_class = engine_map[engine_cfg.pop('class')]
        engine = engine_class(**engine_cfg)
        engines.append(engine)

    arena(engines)


def run_bm(args):
    engine_name, *engine_args = args.engine.split(':')
    engine_class = engine_map[engine_name]
    engine = engine_class(*engine_args)
    engine.choose(Board())
    
    
if __name__ == '__main__':
    sys.exit(main())
