#!/usr/bin/env python
import sys

from c4.board import DRAW
from c4.engine import NegamaxEngine, AlphaBetaEngine
from c4.game import GameHandler


def main():
    engine2 = AlphaBetaEngine(2)
    engine1 = NegamaxEngine(3)

    game = GameHandler(engine1, engine2, verbose=True)
    b, winner, looser = game.play()
    print b

    if b.end != DRAW:
        print 'Winner: %s' % winner
        
    
if __name__ == '__main__':
    sys.exit(main())
